# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentskillsManager < Formula
  desc "Package manager for agentskills"
  homepage "https://github.com/anverse/agentskills-manager"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anverse/agentskills-manager/releases/download/v0.0.1/agentskills-manager_0.0.1_darwin_amd64.tar.gz"
      sha256 "b38be108b2ce0520e90cadccd09c930890beeb403ae692f472e46ea23b03baf7"

      define_method(:install) do
        bin.install "asm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anverse/agentskills-manager/releases/download/v0.0.1/agentskills-manager_0.0.1_darwin_arm64.tar.gz"
      sha256 "2eca45a9acb6dd62fea02b5c9bfa53cf0c325af2867b80bc32f79a395ac68cb4"

      define_method(:install) do
        bin.install "asm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anverse/agentskills-manager/releases/download/v0.0.1/agentskills-manager_0.0.1_linux_amd64.tar.gz"
      sha256 "1173166924206a4531eba7f91b3b7373790f00dac8c164b66fb10aa61b020a8e"
      define_method(:install) do
        bin.install "asm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anverse/agentskills-manager/releases/download/v0.0.1/agentskills-manager_0.0.1_linux_arm64.tar.gz"
      sha256 "37a7009c6cad27ac6b7388d804f2e39dff3f67979b9e1be33a98bf4876dfa8ae"
      define_method(:install) do
        bin.install "asm"
      end
    end
  end

  test do
    system "#{bin}/asm", "--version"
  end
end
