# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NebulaPki < Formula
  desc "Declarative wrapper around nebula-cert"
  homepage "https://github.com/anverse/nebula-pki"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anverse/nebula-pki/releases/download/v0.1.6/nebula-pki_0.1.6_darwin_amd64.tar.gz"
      sha256 "777341153401589380800653b80972319edaeefee439408788dc92272c292c15"

      define_method(:install) do
        bin.install "nebula-pki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anverse/nebula-pki/releases/download/v0.1.6/nebula-pki_0.1.6_darwin_arm64.tar.gz"
      sha256 "2c7dc12d9b7a6a10533da81dae72c5c4361a83e307a7a74b698b54bf4f763dd0"

      define_method(:install) do
        bin.install "nebula-pki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anverse/nebula-pki/releases/download/v0.1.6/nebula-pki_0.1.6_linux_amd64.tar.gz"
      sha256 "5783199a18ac6ae41432e98d0a6908ebbcb7500ce1556c21b1e5853cd96f7931"
      define_method(:install) do
        bin.install "nebula-pki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anverse/nebula-pki/releases/download/v0.1.6/nebula-pki_0.1.6_linux_arm64.tar.gz"
      sha256 "6db4023ca91ac359911147c3b5750e72454d6f4dea6cb4527e2141fe98ae8d2a"
      define_method(:install) do
        bin.install "nebula-pki"
      end
    end
  end

  test do
    system "#{bin}/nebula-pki", "--version"
  end
end
