# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NebulaPki < Formula
  desc "Declarative wrapper around nebula-cert"
  homepage "https://github.com/anverse/nebula-pki"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anverse/nebula-pki/releases/download/v0.1.7/nebula-pki_0.1.7_darwin_amd64.tar.gz"
      sha256 "ebb19be7f8f2a42e2d5722a5355339348f6f72321622d27913907ef7b20eadab"

      define_method(:install) do
        bin.install "nebula-pki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anverse/nebula-pki/releases/download/v0.1.7/nebula-pki_0.1.7_darwin_arm64.tar.gz"
      sha256 "fa12b1ff3640d56872d3ae2aff7b9cb037147018fd691f0f8a2c9f7890ec3143"

      define_method(:install) do
        bin.install "nebula-pki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anverse/nebula-pki/releases/download/v0.1.7/nebula-pki_0.1.7_linux_amd64.tar.gz"
      sha256 "283e3ce9c2ad7f685002239416a3500e228d091ed9029dbb74323a653d57922e"
      define_method(:install) do
        bin.install "nebula-pki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anverse/nebula-pki/releases/download/v0.1.7/nebula-pki_0.1.7_linux_arm64.tar.gz"
      sha256 "21e616aa386134f209db9f1b334fdd0384e62574d1408b4e30f0fd9e69462289"
      define_method(:install) do
        bin.install "nebula-pki"
      end
    end
  end

  test do
    system "#{bin}/nebula-pki", "--version"
  end
end
